spring.application.name=Spring-1

spring.thymeleaf.cache=false

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/ProyectoSpring
#Esto no va y se crea una nueva base de datos llamada test
spring.data.mongodb.database=ProyectoSpring